# markdownlint-cli2 configuration
config:
  MD033: false  # Allow inline HTML
  MD041: false  # Allow first line to not be h1 (for centered title)
  MD059: false  # Allow link text flexibility
  MD013:
    line_length: 80
    code_blocks: false  # Don't check code blocks
    tables: false  # Don't check tables
    headings: false  # Don't check headings
    html: false  # Don't check HTML lines
