# markdownlint-cli2 configuration
config:
  MD033: false  # Allow inline HTML
  MD013: false  # Allow long lines
  MD041: false  # Allow first line to not be h1 (for centered title)
  MD059: false  # Allow link text flexibility
